URL_BASIC_LIVERPOOL_STATS: https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
STANDARD_STATISTICS: Standard Stats
SCORES_AND_FIXTURES: Scores & Fixtures
SHOOTING_STATS: Shooting
GOAL_SHOT_CREATION: Goal and Shot Creation
#  URL_ADV_LIVERPOOL: